# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 15:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boletin', '0002_auto_20160530_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrado',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='myfolder/'),
        ),
    ]
